/**
 * Declarations → CSS. The live preview and the exported stylesheet both come
 * through here, so what you see on the canvas is literally what ships.
 */

import type { Declaration, Mode, ResolvedTokens } from "../engine/types"

export function declarationBlock(declarations: Declaration[], selector: string): string {
    const body = declarations.map(([name, value]) => `    ${name}: ${value};`).join("\n")
    return `${selector} {\n${body}\n}`
}

/**
 * The first family in a CSS stack — the one an `@font-face` rule has to be
 * named after for the stack to pick it up. `"Geist", ui-sans-serif, …` → `Geist`.
 */
export function primaryFamily(stack: string): string {
    const first = stack.split(",")[0]?.trim() ?? ""
    return first.replace(/^["']|["']$/g, "")
}

const FORMATS: Record<string, string> = {
    woff2: "woff2",
    woff: "woff",
    ttf: "truetype",
    otf: "opentype",
}

/**
 * `@font-face` rules for uploaded files. `assetBase` differs by consumer — the
 * app serves assets from an API route, the export sits next to a folder — so the
 * rules are generated per destination rather than baked with one path.
 */
export function fontFaceCss(resolved: ResolvedTokens, assetBase: string): string {
    const files = resolved.config.typography.fontFiles ?? []
    if (files.length === 0) return ""

    return files
        .map((file) => {
            const family = primaryFamily(resolved.config.typography.families[file.family] ?? "")
            const extension = file.fileName.split(".").pop()?.toLowerCase() ?? "woff2"
            const format = FORMATS[extension] ?? "woff2"
            return [
                `@font-face {`,
                `    font-family: "${family}";`,
                `    src: url("${assetBase}/${encodeURIComponent(file.fileName)}") format("${format}");`,
                `    font-weight: ${file.weight};`,
                `    font-style: ${file.style};`,
                // swap, so text is readable while the file loads rather than invisible.
                `    font-display: swap;`,
                `}`,
            ].join("\n")
        })
        .join("\n\n")
}

/**
 * The preview scopes tokens to its own root instead of `:root`, so the brand
 * never leaks into the app's own chrome. Same declarations, different selector.
 */
export function previewCss(
    resolved: ResolvedTokens,
    rootSelector = "#preview-root",
    assetBase?: string,
): string {
    return [
        // @font-face cannot be scoped to a selector, so it is emitted globally —
        // harmless, since the family name only takes effect where the token points.
        assetBase ? fontFaceCss(resolved, assetBase) : "",
        declarationBlock(resolved.declarations.light, rootSelector),
        declarationBlock(resolved.declarations.dark, `${rootSelector}[data-theme="dark"]`),
    ]
        .filter(Boolean)
        .join("\n\n")
}

/**
 * Tailwind v4 exposes tokens as CSS variables under known namespaces, so an
 * `@theme inline` block that forwards our semantics turns them into utilities
 * (`bg-background`, `text-muted-foreground`, `rounded-md`) with no config file.
 */
function themeBlock(resolved: ResolvedTokens): string {
    const lines: string[] = []
    for (const token of resolved.semantics) {
        lines.push(`    --color-${token.name}: var(--${token.name});`)
    }
    for (const [name, value] of resolved.declarations.light) {
        if (
            name.startsWith("--radius-") ||
            name.startsWith("--space-") ||
            name.startsWith("--container-") ||
            name.startsWith("--shadow-") ||
            name.startsWith("--ease-") ||
            name.startsWith("--font-") ||
            name.startsWith("--text-")
        ) {
            lines.push(`    ${name}: var(${name});`)
        } else if (name.startsWith("--breakpoint-")) {
            // Literal, never `var()`. Tailwind builds its variants into
            // `@media` rules, and a custom property does not resolve there —
            // `@media (width >= var(--breakpoint-lg))` is invalid, so every
            // `lg:` utility silently stops applying. Verified against a real
            // Tailwind v4 build; this is the same trap the docs warn about.
            lines.push(`    ${name}: ${value};`)
        }
    }
    return `@theme inline {\n${lines.join("\n")}\n}`
}

export function toTokensCss(resolved: ResolvedTokens, options: { darkMedia?: boolean } = {}): string {
    const { meta } = resolved.config
    const header = [
        `/*`,
        ` * ${meta.name} — design tokens`,
        ` * Generated by Brand Forge. Do not edit by hand; edit the brand and re-export.`,
        ` *`,
        ` * Semantic tokens alias primitives, so a colour value appears exactly once per mode.`,
        ` * Use the semantic names. Reach for a primitive only when no semantic fits.`,
        ` *`,
        ` * The --color-* names in the @theme block at the bottom are Tailwind's, and exist only`,
        ` * inside it. In hand-written CSS use var(--primary), not var(--color-primary) — the`,
        ` * latter resolves to nothing and the declaration is dropped without an error.`,
        ` */`,
    ].join("\n")

    const parts = [
        header,
        // Assets ship beside the stylesheet in the export tree.
        fontFaceCss(resolved, "./assets"),
        // `[data-theme="light"]` is spelled out rather than left to fall through
        // to `:root`. A toggle that writes "light" to get back from dark worked
        // only by accident before, and an accident is a thing that stops working.
        declarationBlock(resolved.declarations.light, ':root,\n[data-theme="light"]'),
        declarationBlock(resolved.declarations.dark, '[data-theme="dark"]'),
    ]

    // Off by default. Shipping a prefers-color-scheme block alongside the
    // attribute makes the docs' "dark mode is an attribute, not a media query"
    // a lie, and worse: on a dark-preference OS a toggle that only removes
    // `data-theme` can never get back to light. Opt in knowingly or not at all.
    if (options.darkMedia === true) {
        parts.push(
            `@media (prefers-color-scheme: dark) {\n${indent(
                declarationBlock(resolved.declarations.dark, ':root:not([data-theme="light"])'),
            )}\n}`,
        )
    }

    parts.push(themeBlock(resolved))
    // filter: no @font-face means no empty gap where it would have been.
    return parts.filter(Boolean).join("\n\n") + "\n"
}

const indent = (block: string): string =>
    block
        .split("\n")
        .map((line) => `    ${line}`)
        .join("\n")

export const modeSelector = (mode: Mode): string =>
    mode === "light" ? ":root" : '[data-theme="dark"]'
