/**
 * DESIGN_SYSTEM.md — the declarative reference an agent reads before it writes.
 *
 * Written deviation-first. A model arrives with strong priors (shadcn's token
 * names, Tailwind's spacing, `h1`-style type roles); the highest-value content
 * is therefore where THIS system contradicts those priors, not where it agrees.
 * Everything is a copy-pasteable value, and every rule that can be shown wrong
 * as well as right is.
 */


import { apca, CHART_MIN_DELTA_E, COLLISION_DELTA_E, composite, deltaE, LC_THRESHOLD, SYNTAX_MIN_DELTA_E } from "../engine/contrast"
import { spaceName } from "../engine/defaults"
import { SCALE_ROLES, type ResolvedTokens, type SemanticGroup } from "../engine/types"
import { chartPlanFor, scaleInkFor } from "../engine/semantics"
import { primaryFamily } from "./css"
import { table, deviations, cellValue, tokenTable, labelPairsFor, SHADCN_NAMES, GROUP_TITLES, GROUP_ORDER } from "./mdHelpers"
import { componentRecipes, wrongRight } from "./sections/recipes"
import { codeSection } from "./sections/code"
import { chartSection } from "./sections/chart"
import { collisions, notDefined } from "./sections/audit"
import { assetsSection, layoutSection } from "./sections/layoutAssets"

export function toDesignSystemMd(resolved: ResolvedTokens): string {
    const { config } = resolved
    const { meta } = config

    /**
     * The fills that differ from their own ground by hue alone — generated,
     * because "Lc 0.0" was typed in from one acceptance run's measurement and is
     * a claim about one palette. DECISIONS #31 applies to a sentence defending a
     * rule as much as to one quoting a token.
     */
    const byName = new Map(resolved.semantics.map((token) => [token.name, token]))
    const hueOnly = ([fill, ground]: [string, string]): string | undefined => {
        const token = byName.get(fill)
        const groundToken = byName.get(ground)
        if (!token || !groundToken) return undefined
        const groundHex = groundToken.values.dark!.hex
        const { alpha } = token.dark
        const hex =
            alpha === undefined
                ? token.values.dark!.hex
                : composite(token.values.dark!.hex, alpha, groundHex)
        return `\`--${fill}\` on \`--${ground}\` is Lc ${Math.abs(apca(hex, groundHex)).toFixed(1)}`
    }
    const HUE_ONLY = (
        [
            ["state-selected", "surface"],
            ["primary-subtle", "surface"],
            ["success-subtle", "surface-sunken"],
        ] as Array<[string, string]>
    )
        .map(hueOnly)
        .filter(Boolean)
        .join(", ")

    // Name the companion properties, not just their values: an agent that can't
    // see the token name will invent a number for line-height.
    const typeRows = config.typography.roles.map((role) => [
        `\`--text-${role.role}\``,
        // The family is part of applying a role, not a separate lookup. Omitting
        // this column is how a display face ends up rendered in the body font.
        `\`--font-${role.family}\``,
        role.minSizeRem === undefined
            ? `${role.sizeRem}rem`
            : `**fluid** ${role.minSizeRem}–${role.sizeRem}rem`,
        `\`--text-${role.role}--line-height\` · ${role.lineHeight}`,
        `\`--text-${role.role}--font-weight\` · ${role.weight}`,
        `\`--text-${role.role}--letter-spacing\` · ${role.tracking ?? "normal"}`,
    ])

    const motionRows = [
        ...Object.entries(config.motion.durations).map(([name, ms]) => [
            `\`--duration-${name}\``,
            `${ms}ms`,
        ]),
        ...Object.entries(config.motion.easings).map(([name, curve]) => [
            `\`--ease-${name}\``,
            `\`${curve}\``,
        ]),
    ]

    return `# ${meta.name} — design system

${meta.domain ? `For ${meta.domain}. ` : ""}Generated by Brand Forge from \`brands/${meta.slug}.json\`.
Do not edit this file by hand — edit the brand and re-export.
${meta.voice.length > 0 ? `\nThe voice is ${meta.voice.join(", ")}. Let that show in copy and restraint, not in decoration.\n` : ""}
## 🚨 Read this first — where this system contradicts the defaults

${deviations(resolved)
    .map((note) => `- ${note}`)
    .join("\n")}

## How the layers work

Two layers, and only one of them is yours to use.

**Primitives** — \`--primary-50\` … \`--primary-950\` across ${Object.keys(resolved.scales).length} ramps
(${Object.values(resolved.scales)
        .map((scale) => `\`${scale.role}\``)
        .join(", ")}), 11 steps each, generated in OKLCH. They exist so a human can tune colour.
**Do not reference them in code.**

**Semantics** — the ${resolved.semantics.length} tokens below. Every one aliases a primitive, and
re-points itself in dark mode. This is the whole API.

${GROUP_ORDER.map((group) => `### ${GROUP_TITLES[group]}\n\n${tokenTable(resolved, group)}`).join("\n\n")}

## Type

${table(["Token", "Family", "Size", "Line height", "Weight", "Tracking"], typeRows)}

Families: \`--font-sans\` is \`${config.typography.families.sans}\`, \`--font-mono\` is
\`${config.typography.families.mono}\`${
        config.typography.families.display
            ? `, and \`--font-display\` is \`${config.typography.families.display}\``
            : ""
    }.

${
        config.typography.families.display
            ? `**\`--font-display\` is a different typeface, not a bigger weight of the body font.** It is
drawn for size and belongs on the \`display\` role only. Do not set it on headings, buttons or body
copy${
                  (config.typography.fontFiles ?? []).some((file) => file.family === "display")
                      ? `, and note it ships in only ${[
                            ...new Set(
                                (config.typography.fontFiles ?? [])
                                    .filter((file) => file.family === "display")
                                    .map((file) => file.weight),
                            ),
                        ].join(", ")} — asking for a weight it doesn't have gets you a browser-synthesised fake bold, which looks wrong in a way people notice without being able to name`
                      : ""
              }.\n`
            : ""
    }${
        config.typography.roles.some((role) => role.minSizeRem !== undefined)
            ? `### Fluid roles

${config.typography.roles
                  .filter((role) => role.minSizeRem !== undefined)
                  .map(
                      (role) =>
                          `\`--text-${role.role}\` scales from **${role.minSizeRem}rem** to **${role.sizeRem}rem**`,
                  )
                  .join(", and ")} across the viewport range
${config.typography.fluidRange?.minPx ?? 390}px – ${config.typography.fluidRange?.maxPx ?? 1280}px.
Below and above that span they hold at the ends.

They emit a \`clamp()\`, so **there is nothing to do** — no media queries, no overrides. What you
must not do is replace one with a fixed size:

\`\`\`css
/* ✅ */
h1 { font-size: var(--text-display); }

/* ❌ pins the fluid role to its desktop size — a 56px heading on a phone */
h1 { font-size: 3.5rem; }
@media (min-width: 768px) { h1 { font-size: var(--text-display); } }
\`\`\`

The middle term of each \`clamp()\` deliberately mixes \`rem\` with \`vw\` rather than being pure
\`vw\`. Viewport units ignore the reader's font-size preference, so a \`vw\`-only heading refuses to
grow when someone zooms — a failure that is invisible on every device you own and obvious to
somebody who needs it.\n`
            : ""
    }

${
        config.typography.fontLinks && config.typography.fontLinks.length > 0
            ? `**The faces have to be loaded or the stack silently falls back to system fonts.** Put this in \`<head>\`:\n\n\`\`\`html\n${config.typography.fontLinks.map((href) => `<link rel="stylesheet" href="${href}">`).join("\n")}\n\`\`\``
            : `**No webfont source is declared**, so the named families only render where they are already installed. Everything else falls back to the system stack. Load them yourself, or say so.`
    }

## Brand assets

${assetsSection(resolved)}

## Layout — breakpoints and containers

${layoutSection(resolved)}

## Space, radius, elevation

Spacing runs on a ${config.spacing.basePx}px grid, blessed subset only:
${config.spacing.blessed.map((px) => `\`--space-${spaceName(px, config.spacing.basePx)}\` (${px}px)`).join(", ")}.

Radius derives from a single ${config.radius.basePx}px base:
${Object.entries(resolved.radius)
        .map(([step, px]) => `\`--radius-${step}\` ${step === "full" ? "9999px" : `${px}px`}`)
        .join(", ")}.

**Concentric radius.** \`inner = outer − padding\`, floored at 0.
A card at \`--radius-lg\` (${resolved.radius.lg}px) with \`--space-4\` (16px) padding holds children at ${Math.max(0, resolved.radius.lg - 16)}px.

**A row of siblings is one flush block, not three separate cases.** Three cards side by side inside
a padded container give a left-flush child, a right-flush child, and a middle one touching neither —
which read as three different radii if you apply the rule per element. They are one row: compute the
formula once for the row and give every child in it the same value. The same holds for a two-up
field pair in a form.

**It governs boxes flush against the parent's inner edge — nothing else.** Flush means touching the
padding on both sides. An element that floats inside the padding with space around it — a badge, an
inline \`<code>\`, a chip, an auto-width button — is not concentric with anything and keeps its own
radius. **A full-width control is flush and does follow the formula**, even though it is a control:
a stretched button at the bottom of a card squares off, the same button sized to its label does not.

Everything full-width inside a padded card *is* flush, and that is most of a form: inputs, banners,
nested panels, tables. Inside this card (\`--radius-lg\` ${resolved.radius.lg}px, \`--space-6\` 24px
padding) the formula gives 0, so **those elements are square**, and the recipes below that specify
\`--radius-md\` for an Input or an Alert describe them standing on the page, not nested in a card.
When the two disagree, concentric wins — it is the more specific statement.

If square-edged fields inside rounded cards is not the look you want, that is a real tension and the
fix is a smaller card radius or a padding change, not an exception. Note the formula can also
produce values off the radius scale (a 15px panel with 8px padding gives 7px); that is expected —
use the computed number, don't snap it.

Elevation is \`--shadow-sm\` | \`--shadow-raised\` | \`--shadow-overlay\`, and the last two are named for the surface they pair with — \`--surface-raised\` and \`--surface-overlay\`. Never mix a surface with another level's shadow. In dark mode
\`--shadow-sm\` becomes a hairline ring and nothing else — but \`--shadow-raised\` and
\`--shadow-overlay\` keep a real drop shadow *and* gain a ring, because at those levels the surface
lift alone is not enough separation. Do not assume "dark mode has no shadows"; check the token.
Use shadow for things that float and \`--border\` for things that divide; never both for the same
job.

## Motion

${table(["Token", "Value"], motionRows)}

Enter with \`--duration-base\` and \`--ease-out\`; leave with \`--duration-fast\`. Exits are always
quicker than entrances. Name the properties you transition — never \`transition: all\`.

## Component recipes

${componentRecipes(resolved)}

## Wrong and right

${wrongRight(resolved)}

## Tokens that currently share a value

${collisions(resolved)}

## What this system does not define

${notDefined(resolved)}

## Editorial — running text, figures and code

The component recipes above are app-shaped: buttons, cards, tables, dialogs. A page that is mostly
*prose* needs different answers.

None of this is new tokens. It is the existing spacing scale and type roles composed for reading.

**Measure.** Running text takes \`--container-prose\`. Large type — a hero headline, a section
intro, a pull quote — takes \`--container-intro\` (${
        resolved.config.layout.containers.find((c) => c.name === "intro")?.maxRem ?? 52
    }rem), which exists because a display headline
wraps to five lines at the reading measure and is unreadable at page width. Both nest inside a
wider frame; neither ever spans the viewport.

**Vertical rhythm.** Space below a heading is always smaller than the space above it, so a heading
belongs to the text it introduces rather than floating between two blocks:

\`\`\`css
p                { margin-block: var(--space-6); }        /* 24px */
h2               { margin-block: var(--space-16) var(--space-4); }  /* 64px above, 16px below */
h3               { margin-block: var(--space-12) var(--space-3); }
figure, pre      { margin-block: var(--space-8); }
blockquote       { margin-block: var(--space-12); }
li               { margin-block: var(--space-2); }
\`\`\`

**Lists.** \`padding-left: var(--space-6)\`. Set the marker in \`--muted-foreground\`, not
\`--foreground-tertiary\` — tertiary is below the reading threshold and a marker is part of the
sentence.

**Blockquote.** A \`3px\` rule in \`--border-strong\` on the leading edge, \`padding-left:
var(--space-6)\`, set at \`body-lg\`. Attribution goes in \`body-sm\` / \`--muted-foreground\`. Do
not italicise the whole quote; long italic runs are slower to read.

**Figures and media.** Caption in \`body-sm\` / \`--muted-foreground\`, \`margin-top:
var(--space-3)\`. A full-width figure sits in \`--container-wide\`; a figure in the text column stays
in \`--container-prose\`.

**Media geometry**, because otherwise every page picks its own:

- **Aspect ratio is one of three.** \`16 / 9\` for anything video-shaped, \`3 / 2\` for photography,
  \`1 / 1\` for avatars, logos and thumbnails. Set \`aspect-ratio\` and \`object-fit: cover\` rather
  than a fixed height, so the box holds its shape at every width. Anything else is a one-off — say so.
- **A figure takes \`--radius-lg\`** when it sits inside the text column, and **no radius at all when
  it is full-bleed** — a rounded corner against the window edge reads as a mistake. Inside a padded
  card the concentric rule wins over both.
- **A caption aligns to the text column, never to the figure.** A full-bleed image with its caption
  centred under it at ${resolved.config.layout.containers.find((c) => c.name === "wide")?.maxRem ?? 90}rem
  is a caption nobody reads at the same measure as the prose around it. Set the caption to
  \`--container-prose\` and left-align it with the body text; only the image escapes the column.

**A placeholder standing in for an image must be \`--muted\`, not \`--surface-sunken\`.** Sunken is
opaque and collapses into \`--background\` in dark mode, so the placeholder disappears and only its
border survives. \`--muted\` is translucent and reads on any surface in both modes. (A code block is
the opposite case: it *is* \`--surface-sunken\`, and it carries a border for exactly this reason.)

**Section breaks.** An \`<hr>\` is \`border: 0\` plus \`border-top: 1px solid var(--border)\` and
\`margin-block: var(--space-16)\` — the same 64px that sits above an \`h2\`, because a rule and a
heading are both saying "new section" and two different gaps for one idea reads as an accident.
Never \`--border-subtle\`: that one is defined as below the visible threshold and is for separating
rows inside an already-bounded area, which is the opposite of dividing two regions.

**In-page anchors under sticky chrome.** A documentation page is mostly \`#anchor\` links, and a
fixed header hides the heading they land on. One rule fixes every anchor on the page:

\`\`\`css
html { scroll-padding-top: calc(var(--shell-header) + var(--space-4)); }
\`\`\`

Use \`scroll-padding-top\` on the scroll container, not \`scroll-margin-top\` on every heading — the
second is the same fix written once per element and drifts the moment somebody adds a heading. If the
page has no fixed header, the rule is harmless.

**Button sizes.** The Button recipe above is the default: 40px, \`label\`. A marketing call to action
at 13px is not a call to action. A large button is 52px tall, \`padding-inline: var(--space-8)\`, set
at \`body-lg\` with the \`label\` weight — same colours, same radius, same states. Those are the two
*designed* sizes; the 44px touch variant of the default is the same button with a bigger hit area,
not a third size.

**The mark has a floor.** Below about 24px of height the accent path stops reading as a flourish and
becomes a smudge against the wordmark. Above that it is fine. If you need the brand smaller than
that, use the wordmark path alone.

**Container gutter.** \`padding-inline: var(--space-6)\`, widening to \`var(--space-8)\` from the
\`md\` breakpoint. A container caps width; it does not give itself breathing room at the edge of a
phone.

**A marketing header uses \`--shell-header\`.** The token is described as app chrome, and the
question of whether a landing page may take it has a definite answer: yes, and it should. One header
height in the system is the point of having the token — a marketing site at 72px next to an app at
${(resolved.config.layout.shell.find((d) => d.name === "header")?.rem ?? 3.5) * 16}px is the drift
the token exists to prevent, and it is visible the moment somebody navigates from one to the other.
A taller marketing header is a deliberate deviation: state it, don't drift into it.

**Footer.** \`--inverse\` is documented as a footer band and four \`inverse-*\` tokens exist for what
goes on it; the layout does not, so here it is.

- **Three or four link columns plus a brand column**, in a \`grid\` with
  \`gap: var(--space-8)\`, collapsing to one column below \`md\` — not two, because a two-column
  footer on a phone puts two link lists at the same eye level with nothing separating them.
- **The brand column is wider**: \`grid-template-columns: 2fr 1fr 1fr 1fr\` at \`lg\` and above. It
  holds the mark, one line of blurb in \`--inverse-muted-foreground\` at \`body-lg\`, and nothing else.
- **A column heading is \`label\` in \`--inverse-foreground\`**, not
  \`--inverse-muted-foreground\`: that one is held to the large-text bar, and \`label\` is neither
  \`body-lg\` nor \`body\` at weight 600. \`--inverse-muted-foreground\` is for the brand
  column's blurb, which *is* set at \`body-lg\`${
        resolved.config.typography.roles.find((r) => r.role === "label")?.transform === "uppercase"
            ? ", uppercase, because this brand's `label` role is"
            : " — the `label` role on this brand is not uppercase, so do not make it so here"
    }.
- **The links under it are \`body-sm\` in \`--link-inverse\`, and are not underlined at rest.** They are a navigation
  list, not links in running text — the underline rule applies to prose. Underline on hover.
- **Fine print — copyright, legal — takes \`--inverse-foreground\`, not
  \`--inverse-muted-foreground\`.** The muted one is held to the large-text bar only, so it cannot
  carry small print. Fine print on an inverse band is not quiet in this system, and that is the
  honest trade rather than an oversight.
- The band is full-bleed; its contents sit in \`--container-page\` with the standard gutter, and it
  gets \`padding-block: var(--space-16)\`. Separate the fine-print row with \`--inverse-border\`.

## Code samples

${codeSection(resolved)}

## Charts and data

${chartSection(resolved)}

## Stacking order

Every layer that can overlap another has a number here. Writing a raw \`z-index\` is how two
components end up fighting and the loser is whoever shipped last.

${table(
        ["Token", "Value", "What lives here"],
        resolved.config.layout.zLayers.map((layer) => [`\`--z-${layer.name}\``, String(layer.value), layer.note]),
    )}

Two of these are load-bearing and easy to get wrong. \`--z-modal\` sits **ten** above \`--z-scrim\`,
not a hundred: a dialog belongs immediately on top of its own backdrop and nothing should ever land
between them. And \`--z-toast\` deliberately outranks \`--z-modal\` — a confirmation that renders
behind the dialog that triggered it is invisible exactly when someone needs it.

## App frame

\`--container-*\` bounds the page. These bound its furniture — the numbers every implementation
otherwise invents, differently, on each screen.

${table(
        ["Token", "Value", "What it is"],
        resolved.config.layout.shell.map((dimension) => [
            `\`--shell-${dimension.name}\``,
            `${dimension.rem}rem (${dimension.rem * 16}px)`,
            dimension.note,
        ]),
    )}

## Outside a browser

Everything above assumes CSS custom properties, \`oklch()\`, \`rgba()\` and a \`data-theme\`
attribute you control. **An HTML email has none of those**, and neither does a favicon pipeline, a
native app, a PDF or a canvas render. The system still applies; the delivery does not.

**Take the literals from \`tokens.json\`, not from these tables.** Its root \`$extensions\` block
carries \`resolved.light\` and \`resolved.dark\`: every semantic token as a hex, and every
translucent one as \`{ hex, alpha, css, composited }\` where \`composited\` is what the wash
actually becomes over each surface it is allowed on, blended source-over in sRGB — which is what a
browser does and the only usable form where \`rgba()\` is not available. Reading it is one lookup;
resolving the aliases yourself is a second implementation of the mapping, and a second implementation
is what this whole system is arranged to avoid.

\`\`\`html
<!-- ✅ the literal, with the token name kept beside it so the intent survives -->
<td style="background:${
        resolved.semantics.find((t) => t.name === "primary")?.values.light!.hex ?? "#000000"
    };color:${
        resolved.semantics.find((t) => t.name === "primary-foreground")?.values.light!.hex ?? "#ffffff"
    }"><!-- --primary / --primary-foreground -->

<!-- ❌ var() with a fallback is a *browser* degradation pattern. Outlook on Windows
     renders through the Word engine, which fails to parse var() at all and drops
     the whole declaration — fallback included. You get no colour. -->
<td style="background:var(--primary, ${
        resolved.semantics.find((t) => t.name === "primary")?.values.light!.hex ?? "#000000"
    })">
\`\`\`

Four more things that change, all of them worth knowing before you start rather than after:

- **Dark mode.** \`tokens.css\` keys dark on \`[data-theme="dark"]\` only, deliberately — a
  \`prefers-color-scheme\` block alongside it would make "dark mode is an attribute" untrue and
  would trap anyone whose OS prefers dark and whose toggle only removes the attribute. In a medium
  where you cannot set the attribute, that leaves you writing a \`prefers-color-scheme\` layer by
  hand from \`resolved.dark\`. That is the one place overriding a colour is not a mistake, and it
  is the *only* one.
- **The mark.** Inline SVG is stripped by most mail clients, so it ships as a \`data:\` URI
  \`<img>\` — and inside one, \`currentColor\` resolves to black rather than the surrounding ink.
  Bake one image per ground you need (foreground and inverse, light and dark), and give it real
  \`alt\` text, because images are blocked by default in most clients and this system defines no
  wordmark-in-type fallback.
- **Fluid type has no \`clamp()\`.** Freeze the role at your fixed width and say which width. At
  600px, \`--text-display\` is ${(() => {
      const role = resolved.config.typography.roles.find((r) => r.role === "display")
      if (!role?.minSizeRem) return "—"
      const range = resolved.config.typography.fluidRange ?? { minPx: 390, maxPx: 1280 }
      const slope = (role.sizeRem - role.minSizeRem) / (range.maxPx / 16 - range.minPx / 16)
      const intercept = role.minSizeRem - slope * (range.minPx / 16)
      const at = Math.min(Math.max(role.minSizeRem, intercept + slope * (600 / 16)), role.sizeRem)
      return `${(at * 16).toFixed(0)}px`
  })()} and \`--text-heading-lg\` is ${(() => {
      const role = resolved.config.typography.roles.find((r) => r.role === "heading-lg")
      if (!role?.minSizeRem) return "—"
      const range = resolved.config.typography.fluidRange ?? { minPx: 390, maxPx: 1280 }
      const slope = (role.sizeRem - role.minSizeRem) / (range.maxPx / 16 - range.minPx / 16)
      const intercept = role.minSizeRem - slope * (range.minPx / 16)
      const at = Math.min(Math.max(role.minSizeRem, intercept + slope * (600 / 16)), role.sizeRem)
      return `${(at * 16).toFixed(0)}px`
  })()}.
- **The font stack does not degrade the way it does on the web.** Outlook takes the *first* family
  named and falls back to Times New Roman rather than walking the list, and no \`<link>\` survives
  to load a webfont — so \`${config.typography.families.sans}\` delivers a serif. Name a websafe
  family first in that medium (\`Arial, Helvetica, sans-serif\`) and accept that the brand face is
  not part of the design there.

**The container and shell tokens do not translate either.** A 600px email is narrower than every
container in the set and narrower than \`--shell-table-min\`, whose remedy — an \`overflow-x\`
wrapper — does nothing in mail. Use the spacing scale, the type roles and the colours; treat the
layout tokens as inapplicable and say so rather than picking the nearest one.

## Contrast

Text pairs are validated with APCA (Lc), which unlike WCAG 2 models dark-mode perception correctly.
**Each pair is held to the threshold for its own job, not to a single number:** Lc ${LC_THRESHOLD.body} for body text,
Lc ${LC_THRESHOLD.large} for UI labels and large text, Lc ${LC_THRESHOLD["non-text"]} for non-text boundaries.

${(() => {
        const distinct = resolved.warnings.filter((w) => w.kind === "distinctness")
        if (distinct.length === 0) return ""
        return `**${distinct.length} pair${distinct.length === 1 ? "" : "s"} of code or chart colours ${distinct.length === 1 ? "is" : "are"} legible and not distinguishable from each other**, which contrast cannot see and this system measures separately:

${distinct.map((warning) => `- ${warning.message}`).join("\n")}

Both colours in each pair are perfectly readable. What you cannot do is rely on the difference between them to carry meaning.

`
    })()}${(() => {
        const contrast = resolved.warnings.filter((w) => w.kind === "contrast")
        if (contrast.length > 0) {
            return `**${contrast.length} pair${contrast.length === 1 ? "" : "s"} in this brand currently miss${contrast.length === 1 ? "es" : ""} its threshold**, listed here because nothing else in this bundle carries them:

${contrast.map((warning) => `- ${warning.message}`).join("\n")}

Do not treat the affected values as validated until they are cleared.`
        }
        return `Every **validated** pair clears its own threshold, in both modes. Three things that
sentence does not mean:

- It is not "every pair clears 75". Labels on solid fills and \`--foreground-secondary\` are held to
  the Lc ${LC_THRESHOLD.large} bar and sit well below the body target — correct for their job, wrong for small body
  copy. Set supporting text below \`body-lg\` in \`--muted-foreground\`.
- \`--border-subtle\` and \`--foreground-tertiary\` are **deliberately exempt**. Both are defined as
  below the visible threshold, so they are not validated and never will be. Neither may be the only
  thing carrying meaning.
- **Every fill in this system is exempt from APCA, and that is a third class the list used to
  omit.** \`--muted\`, the four \`--state-*\` washes and the \`-subtle\` tints are checked for
  *visibility* — that something is there — with a channel-shift measure, because APCA clamps
  everything below its noise floor to 0 and a quiet fill lives entirely in that range. Several of
  them measure **at or near Lc 0 against the surface they land on, differing by hue alone**.
  Measured on this brand in dark: ${HUE_ONLY}. They are visible in colour and invisible in
  greyscale.
  **So the rule the polish rules state for links applies to all of them: colour must never be the
  only marker** (WCAG 1.4.1). A selected row needs a check, a left border or \`aria-selected\` as
  well as its tint; a diff line needs its \`+\`/\`-\`; a badge needs its label to say what it is.
- Pairs nobody declared are not checked. If you compose a combination the token descriptions don't
  sanction — \`--primary\` as body text, \`--muted-foreground\` on \`--surface-raised\` — you are
  outside the validated set and should measure it yourself.

**"Large text" means \`body-lg\` (1.125rem) and up at weight 400, or \`body\` and up at weight 600.**
Below that, the Lc ${LC_THRESHOLD.body} body bar applies.`
    })()}

\`--foreground-tertiary\` is deliberately below the reading threshold. It is for placeholders and
watermarks. If you find yourself wanting it for text a person must read, use \`--muted-foreground\`.
`
}

/** Rough LLM token count — a budget meter for the export dialog. */
export const estimateTokens = (text: string): number => Math.round(text.length / 3.6)

