/**
 * DTCG JSON (W3C design-tokens format, 2025.10).
 *
 * This is an INTEROP artifact, not the source of truth — the typed BrandConfig
 * is. DTCG cannot express generative intent (seeds, chroma curves, the rules
 * that chose a foreground) without abusing `$extensions`, so those live in
 * `$extensions` purely as provenance for a possible future re-import.
 *
 * Modes: DTCG's theming module is still draft, so light and dark ship as two
 * top-level groups. That's a convention, and the file says so rather than
 * pretending otherwise.
 */

import { fluidSize } from "../engine/defaults"
import { composite } from "../engine/contrast"
import { oklchToCss } from "../engine/scale"
import { SCALE_ROLES, STEPS, type Mode, type ResolvedTokens } from "../engine/types"

/** The opaque surfaces a wash is allowed on — the grounds worth pre-compositing. */
const LADDER = ["surface-sunken", "background", "surface", "surface-raised", "surface-overlay"] as const

const EXTENSION = "design.hendri.brandforge"

interface TokenNode {
    $type?: string
    $value?: unknown
    $description?: string
    $extensions?: Record<string, unknown>
    [key: string]: unknown
}

export function toDtcgJson(resolved: ResolvedTokens): string {
    const { config } = resolved

    const colorGroup = (mode: Mode): TokenNode => {
        const primitives: TokenNode = {
            $description: "Generated ramps. Tune colour here; do not reference these from code.",
        }
        for (const role of SCALE_ROLES) {
            const scale = resolved.scales[role]
            if (!scale) continue
            const steps: TokenNode = { $description: `${scale.name} — seeded from ${scale.seed}.` }
            for (const step of STEPS) {
                const swatch = scale.steps[mode][step]!
                steps[String(step)] = {
                    $value: {
                        colorSpace: "oklch",
                        components: [swatch.oklch.l, swatch.oklch.c, swatch.oklch.h],
                        hex: swatch.hex,
                    },
                    ...(swatch.overridden
                        ? { $extensions: { [EXTENSION]: { overridden: true } } }
                        : {}),
                }
            }
            primitives[role] = steps
        }

        const semantics: TokenNode = {
            $description:
                "The consumable layer. Almost everything here aliases a primitive; the translucent tokens state a value, because a DTCG alias cannot carry an alpha.",
        }
        for (const token of resolved.semantics) {
            const { alpha } = token[mode]
            const swatch = token.values[mode]!
            semantics[token.name] = {
                // An alias would drop the alpha and hand every consumer an opaque
                // colour — Figma and Style Dictionary included. A translucent
                // token therefore states its own value, with the alpha in it.
                $value:
                    alpha === undefined
                        ? `{color.${mode}.primitive.${token[mode].scale}.${token[mode].step}}`
                        : {
                              colorSpace: "oklch",
                              components: [swatch.oklch.l, swatch.oklch.c, swatch.oklch.h],
                              alpha,
                              hex: swatch.hex,
                          },
                $description: token.description,
            }
        }

        return { $type: "color", primitive: primitives, semantic: semantics }
    }

    const dimension = (value: number) => ({ $value: { value, unit: "px" } })

    const document: TokenNode = {
        $description: [
            `${config.meta.name} design tokens, generated by Brand Forge.`,
            "Light and dark are separate top-level groups under `color`: the DTCG theming module is",
            "still draft, so modes are a convention here rather than a spec feature.",
        ].join(" "),
        $extensions: {
            [EXTENSION]: {
                schemaVersion: config.$schemaVersion,
                brand: config.meta.slug,
                seeds: Object.fromEntries(config.color.scales.map((s) => [s.role, s.seed])),
                /**
                 * Every semantic as a literal, per mode — the one thing no
                 * shipped artifact carried until acceptance run 11 needed it.
                 *
                 * `tokens.css` contains zero hex values by design (#6: a
                 * semantic aliases its primitive, and the primitive is
                 * `oklch()`), and the DTCG bodies above are alias strings for
                 * the same reason. Both are right for a browser and useless to
                 * every other consumer — an email, a favicon pipeline, a native
                 * app, a PDF. Run 11 had to write the alias resolver itself to
                 * send a newsletter, which meant a second implementation of the
                 * mapping this project exists to keep single.
                 *
                 * Translucent tokens carry `composited`: what the wash actually
                 * becomes over each surface it is allowed on, blended
                 * source-over in sRGB, which is what a browser does. Anywhere
                 * without `rgba()` that is the only usable form, and computing
                 * it by hand is three literals somebody picked.
                 */
                resolved: Object.fromEntries(
                    (["light", "dark"] as Mode[]).map((mode) => [
                        mode,
                        Object.fromEntries(
                            resolved.semantics.map((token) => {
                                const { alpha } = token[mode]
                                const hex = token.values[mode]!.hex
                                if (alpha === undefined) return [token.name, hex]
                                return [
                                    token.name,
                                    {
                                        hex,
                                        alpha,
                                        css: oklchToCss(token.values[mode]!.oklch, alpha),
                                        composited: Object.fromEntries(
                                            LADDER.map((ground) => {
                                                const surface = resolved.semantics.find(
                                                    (candidate) => candidate.name === ground,
                                                )
                                                return [
                                                    ground,
                                                    surface
                                                        ? composite(hex, alpha, surface.values[mode]!.hex)
                                                        : hex,
                                                ]
                                            }),
                                        ),
                                    },
                                ]
                            }),
                        ),
                    ]),
                ),
            },
        },
        color: { light: colorGroup("light"), dark: colorGroup("dark") },
        space: {
            $type: "dimension",
            ...Object.fromEntries(
                config.spacing.blessed.map((px) => [String(px / config.spacing.basePx), dimension(px)]),
            ),
        },
        breakpoint: {
            $type: "dimension",
            $description: "Mobile-first min-widths. A closed set — no max-width breakpoints exist.",
            ...Object.fromEntries(
                config.layout.breakpoints.map((breakpoint) => [
                    breakpoint.name,
                    { ...dimension(breakpoint.minPx), $description: breakpoint.note },
                ]),
            ),
        },
        container: {
            $type: "dimension",
            $description: "Max-widths. Nothing spans the viewport; every region sits in one of these.",
            ...Object.fromEntries(
                config.layout.containers.map((container) => [
                    container.name,
                    {
                        $value: { value: container.maxRem, unit: "rem" },
                        $description: container.note,
                    },
                ]),
            ),
        },
        radius: {
            $type: "dimension",
            ...Object.fromEntries(
                Object.entries(resolved.radius).map(([step, px]) => [step, dimension(px)]),
            ),
        },
        type: {
            $type: "typography",
            $description:
                "A fluid role has no single font size, and DTCG has no way to say so. Its `$value.fontSize` therefore carries the MAXIMUM, and the `$extensions` block beside it carries the minimum and the viewport range that produce the `clamp()` in tokens.css. Read the extension, or read the stylesheet — taking the number alone pins a hero to its desktop size, which is the one thing the reference tells you never to do.",
            ...Object.fromEntries(
                config.typography.roles.map((role) => [
                    role.role,
                    {
                        $value: {
                            fontFamily: config.typography.families[role.family],
                            fontSize: { value: role.sizeRem, unit: "rem" },
                            fontWeight: role.weight,
                            lineHeight: role.lineHeight,
                            // Always emitted, `normal` when unset. A role that
                            // silently omits it is a role somebody copies four
                            // properties from and gets an undefined fifth.
                            letterSpacing: role.tracking ?? "normal",
                        },
                        ...(role.minSizeRem === undefined
                            ? {}
                            : {
                                  $description: `Fluid: ${role.minSizeRem}rem at ${config.typography.fluidRange?.minPx ?? 390}px, ${role.sizeRem}rem at ${config.typography.fluidRange?.maxPx ?? 1280}px. The value above is the maximum only.`,
                                  $extensions: {
                                      [EXTENSION]: {
                                          fluid: {
                                              minSizeRem: role.minSizeRem,
                                              maxSizeRem: role.sizeRem,
                                              minPx: config.typography.fluidRange?.minPx ?? 390,
                                              maxPx: config.typography.fluidRange?.maxPx ?? 1280,
                                              css: fluidSize(
                                                  role.minSizeRem,
                                                  role.sizeRem,
                                                  config.typography.fluidRange,
                                              ),
                                          },
                                      },
                                  },
                              }),
                    },
                ]),
            ),
        },
        // The groups the JSON used to drop in silence. Two acceptance runs found
        // the same hole independently: a pipeline fed from this file lost the
        // stacking order and the app frame, which two hard rules call closed
        // sets, and never knew it.
        shadow: {
            $description:
                "Elevation, named for the surface each level pairs with. Dark mode replaces these — see `tokens.css`; DTCG has no mode-aware shadow.",
            ...Object.fromEntries(
                config.shadows.levels.map((level) => [
                    level.name,
                    { $type: "shadow", $value: level.layers.join(", ") },
                ]),
            ),
        },
        z: {
            $type: "number",
            $description: "The stacking order, as a closed set. Never write a raw z-index.",
            ...Object.fromEntries(
                config.layout.zLayers.map((layer) => [
                    layer.name,
                    { $value: layer.value, $description: layer.note },
                ]),
            ),
        },
        shell: {
            $type: "dimension",
            $description: "The app frame's furniture. `container` bounds the page; these bound its chrome.",
            ...Object.fromEntries(
                config.layout.shell.map((d) => [
                    d.name,
                    { $value: { value: d.rem, unit: "rem" }, $description: d.note },
                ]),
            ),
        },
        opacity: {
            $type: "number",
            $description: "The only two blessed opacities. Neither is for live text.",
            disabled: { $value: config.opacity.disabled },
            loading: { $value: config.opacity.loading },
        },
        brand: {
            $description:
                "Brand artwork, not UI. The one colour in this system that does not change with the mode, because a logo does not.",
            ...(resolved.scales.secondary
                ? {
                      "logo-accent": {
                          $type: "color",
                          $value: {
                              colorSpace: "oklch",
                              components: [
                                  resolved.scales.secondary.steps.light[
                                      resolved.scales.secondary.anchorStep
                                  ]!.oklch.l,
                                  resolved.scales.secondary.steps.light[
                                      resolved.scales.secondary.anchorStep
                                  ]!.oklch.c,
                                  resolved.scales.secondary.steps.light[
                                      resolved.scales.secondary.anchorStep
                                  ]!.oklch.h,
                              ],
                              hex: resolved.scales.secondary.steps.light[
                                  resolved.scales.secondary.anchorStep
                              ]!.hex,
                          },
                          $description:
                              "The accent path of a two-tone mark. Not a UI colour and not validated against any surface.",
                      },
                  }
                : {}),
        },
        font: {
            $type: "fontFamily",
            ...Object.fromEntries(
                Object.entries(config.typography.families)
                    .filter(([, stack]) => Boolean(stack))
                    .map(([name, stack]) => [name, { $value: stack }]),
            ),
        },
        duration: {
            $type: "duration",
            ...Object.fromEntries(
                Object.entries(config.motion.durations).map(([name, ms]) => [
                    name,
                    { $value: { value: ms, unit: "ms" } },
                ]),
            ),
        },
        easing: {
            $type: "cubicBezier",
            ...Object.fromEntries(
                Object.entries(config.motion.easings).map(([name, curve]) => [
                    name,
                    { $value: parseCubicBezier(curve), $description: curve },
                ]),
            ),
        },
    }

    return JSON.stringify(document, null, 2) + "\n"
}

/** DTCG wants the four control points, not the CSS function. */
function parseCubicBezier(curve: string): number[] {
    const match = curve.match(/cubic-bezier\(([^)]+)\)/)
    if (!match) return [0.4, 0, 0.2, 1]
    return match[1]!.split(",").map((part) => Number(part.trim()))
}
