import { describe, expect, it } from 'vitest';
import type { ScanResult } from '@/shared/types';
import { resolveTokens } from './engine/resolve';
import { adoptionPlan, generateConfig, inputsFromScan, isThin, rolesOnScale, tokensPathFor } from './generate';
import { seedBrandFromScan } from './seedFromScan';

const scan = {
  url: 'http://localhost:5173/',
  title: 't',
  scannedAt: 0,
  viewport: { width: 1280, height: 800, dpr: 2 },
  fontFaces: [],
  fontUsage: [
    { family: 'Inter', roles: ['body', 'headings'], variants: [{ size: '16px', weight: '400', lineHeight: '24px', count: 80 }, { size: '32px', weight: '700', lineHeight: '36px', count: 3 }] },
  ],
  colors: [
    { hex: '#BE3A22', usage: ['background'], count: 24, varNames: [] },
    { hex: '#15171B', usage: ['text'], count: 50, varNames: [] },
    { hex: '#FFFFFF', usage: ['background'], count: 9, varNames: [] },
  ],
  gradients: [],
  contrastPairs: [],
  svgs: [],
  customProps: [],
  shape: { radii: [{ value: '6px', count: 12 }], shadows: [], spacing: [{ value: '8px', count: 90 }, { value: '16px', count: 70 }, { value: '24px', count: 20 }] },
  cssText: '',
  unreadableSheets: [],
  stats: { elementsSampled: 10, styleSheets: 1 },
  typeStyles: [],
} as unknown as ScanResult;

describe('generate', () => {
  it('calls a page thin when it has under three colour variables and no type styles', () => {
    expect(isThin(scan)).toBe(true);
    expect(isThin({ ...scan, typeStyles: [{ name: 'h1', form: 'tag', selectorOrUtility: 'h1', fields: {} }] } as ScanResult)).toBe(false);
    expect(isThin({ ...scan, customProps: [{ name: '--a', value: '#111' }, { name: '--b', value: '#222' }, { name: '--c', value: '#333' }] } as ScanResult)).toBe(false);
  });

  it('prefills the inputs from the page, never from a preset', () => {
    const seeded = seedBrandFromScan(scan);
    const inputs = inputsFromScan(scan, seeded);
    expect(inputs.seed.toUpperCase()).toBe('#BE3A22');
    expect(inputs.neutral.toUpperCase()).toBe('#15171B');
    expect(inputs.sans).toContain('Inter');
    expect(inputs.baseSizePx).toBe(16);
    expect(inputs.spacingBasePx).toBe(8);
    expect(inputs.radiusBasePx).toBe(6);
    expect(inputs.shadows).toBe('soft');
  });

  it('puts the roles on a modular scale with line-heights and tracking that follow the size', () => {
    const roles = rolesOnScale(16, 1.25);
    const by = Object.fromEntries(roles.map((r) => [r.role, r]));
    expect(by.body?.sizeRem).toBe(1);
    expect(by.heading?.sizeRem).toBeCloseTo(1.956, 3); // 16 · 1.25³ = 31.25 → 31.3px
    expect(by.display?.sizeRem).toBeCloseTo(3.05, 2);
    expect(by.display?.minSizeRem).toBeCloseTo(2.44, 2);
    expect(by.body?.lineHeight).toBe(1.5);
    expect(by.display!.lineHeight).toBeLessThan(1.2);
    expect(by.display?.tracking).toBe('-0.02em');
    expect(by.code?.family).toBe('mono');
  });

  it('generates a config the engine resolves, with the inputs applied and the rest from the page', () => {
    const seeded = seedBrandFromScan(scan);
    const config = generateConfig(seeded, { ...inputsFromScan(scan, seeded), seed: '#1C7F5C', ratio: 1.333, spacingBasePx: 4, radiusBasePx: 8 }, new Date('2026-09-24'));
    expect(config.color.scales.find((s) => s.role === 'primary')?.seed).toBe('#1C7F5C');
    expect(config.color.scales.find((s) => s.role === 'neutral')?.seed.toUpperCase()).toBe('#15171B');
    expect(config.spacing.basePx).toBe(4);
    expect(config.radius).toMatchObject({ basePx: 8, concentric: true });
    expect(config.meta.deviations.at(-1)).toContain('Generated by Codename on 2026-09-24');
    const resolved = resolveTokens(config);
    expect(resolved.declarations.light.some(([name]) => name === '--primary-600')).toBe(true);
  });

  it('plans which literal becomes which token, exact ones first by use', () => {
    const seeded = seedBrandFromScan(scan);
    const resolved = resolveTokens(seeded);
    const plan = adoptionPlan(scan, resolved);
    const mark = plan.find((a) => a.literal === '#BE3A22');
    // The seed is pinned to its step, so the page's own red is on the ramp exactly.
    expect(mark).toMatchObject({ exact: true, uses: 24 });
    expect(mark?.token).toMatch(/^var\(--primary-\d+\)$/);
    expect(plan.map((a) => a.literal)).toContain('#15171B');
    expect(plan[0]?.uses).toBeGreaterThanOrEqual(plan.at(-1)!.uses);
  });

  it('puts the tokens file beside the entry', () => {
    expect(tokensPathFor('src/index.css')).toBe('src/tokens.css');
    expect(tokensPathFor('app/globals.css')).toBe('app/tokens.css');
    expect(tokensPathFor('style.css')).toBe('tokens.css');
    expect(tokensPathFor(null)).toBe('src/tokens.css');
  });
});
